return {
  "nvim-treesitter/nvim-treesitter",
  opts = function(_, opts)
    -- add more things to the ensure_installed table protecting against community packs modifying it
    opts.ensure_installed = require("astronvim.utils").list_insert_unique(opts.ensure_installed, {
      "bash",
      "bibtex",
      "c",
      "cmake",
      "comment",
      "cpp",
      "css",
      "diff",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "graphql",
      "html",
      "htmldjango",
      "http",
      "ini",
      "javascript",
      "json",
      "json5",
      "latex",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "passwd",
      "python",
      "regex",
      "rust",
      "sql",
      "svelte",
      "terraform",
      "toml",
      "typescript",
      "vimdoc",
      "yaml",
    })
  end,
}
